name: Build wheel in Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . -t artifact-builder -f Dockerfile-llama-cpp-wheel

      - name: Run Docker container
        run: docker run --name my-artifact-builder artifact-builder

      - name: Copy artifact from Docker container
        run: docker cp my-artifact-builder:/build/dist/llama_cpp_python-0.1.49-cp38-cp38-linux_x86_64.whl ./llama_cpp_python-0.1.49-cp38-cp38-linux_x86_64.whl

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./llama_cpp_python-0.1.49-cp38-cp38-linux_x86_64.whl
          token: ${{ secrets.GITHUB_TOKEN }}
